### ISSUE TITLE
Question about faulty types in MircoSS dataset

### ISSUE THREAD

**Issue by zz-bc** [CloudWise-OpenSource/GAIA-DataSet#4]
First of all, thank you for your MicroSS dataset!
After extracting the templates for the run_table _2021-07.csv, I found that there are 16 templates. Except for the two faulty types `[cpu_anomalies]` and `[memory_anomalies]`, I am curious whether the following are considered faulty types:

- "<*>-<*>-<*> <*>:<*>:<*>,<*> | WARNING | <*> | <*> | <*> | [normal memory freed label] lasts ten minutes
- "<*>-<*>-<*> <*>:<*>:<*>,<*> | WARNING | <*> | <*> | <*> | <*> | wait for <*> seconds for follow-up operations to simulate the login failure of the QR code expired
- "<*>-<*>-<*> <*>:<*>:<*>,<*> | ERROR | <*> | <*> | <*> | upload run_logs logs on <*>-<*>-<*> failed: 'str' object does not support item assignment
- "<*>-<*>-<*> <*>:<*>:<*>,<*> | WARNING | <*> | <*> | <*> | trigger the file moving program, start with <*>-<*>-<*> <*>:<*>:<*>.<*>, last for <*> seconds
- "<*>-<*>-<*> <*>:<*>:<*>,<*> | ERROR | <*> | <*> | <*> | upload business logs on <*>-<*>-<*> failed: (pymysql.err.OperationalError) (<*>, 'ny connections')
- "<*>-<*>-<*> <*>:<*>:<*>,<*> | WARNING | <*> | <*> | <*> | trigger an access permission denied exception, will lasts an hour
- "<*>-<*>-<*> <*>:<*>:<*>,<*> | ERROR | <*> | <*> | <*> | upload <*> logs on <*>-<*>-<*> failed: (pymysql.err.OperationalError) (<*>, ""Can't connect to MySQL server on '<*>' ([Errno <*>] Connection refused)"")

**Comment by Xander-cloudwise** [comment]
First of all, thank you for your interest in the GAIA dataset
1、[cpu_anomalies] and [memory_anomalies] are two relatively faulty types of system metric.
2、For "<>-<>-<> <>:<>:<>,<> | WARNING | <> | <> | <> | [normal memory freed label] ", anomaly injection is reflected in changing the system memory usage pattern for a period of time.

The following are the types of anomaly injection for business design, which are reflected in the system business log, the integrity of the call chain, and some KPIs (such as business success rate, average response time). Of course, data cleaning may be needed to the log or call chain.

3、For "<>-<>-<> <>:<>:<>,<> | WARNING | <> | <> | <> | <> | wait for <> seconds for follow-up operations to simulate the login failure of the QR code expired", anomaly injection is reflected in the integrity of a single call chain.
4、For "<>-<>-<> <>:<>:<>,<> | WARNING | <> | <> | <> | trigger the file moving program, start with <>-<>-<> <>:<>:<>.<>, last for <> seconds", anomaly injection is reflected in the change of log mode or the sudden change of the number of error logs after being cleaned into metrics.
5、For "<>-<>-<> <>:<>:<>,<> | WARNING | <> | <> | <> | trigger an access permission denied exception, will lasts an hour", anomaly injection is first reflected in the change of the log mode of a certain node. In addition, based on the label, it will be directly reflected in the metric of business average success rate of call chain cleaning.

So far, the above all are anomaly patterns injected by system itself.Others are several types of error logs printed during system operation. In addition to the patterns you mentioned, all of them can be reflected in the lack of data on that day, which may be caused by failed to upload database.

**Comment by zhangbicheng666** [comment]
Thanks for your reply！
